Use butane 0.6
janosimas/code_as_db pull request #1
Opened 2023-05-12 00:52 UTC by jayvdb

2023-05-12 05:21 UTC, janosimas commented on README.md
> +3. Run `rustup run nightly cargo build`
Since this is explicit in line 11, I don't think it's required.

If you think this is necessary, I prefer to use the format `cargo +nighlty build`.

The same applies to the other occurrences

2023-05-12 05:22 UTC, janosimas requested changes
I prefer to use to format `cargo +nighlty ...` to specify nightly builds

2023-05-12 05:25 UTC, janosimas commented
Just to be clear about it, this project it is currently in stand by.

I plan to come back to but I currently to have the time.

In any case, PRs and issues are welcome. :-)

2023-05-12 05:55 UTC, jayvdb commented
Well I cant update this PR since you have closed it.  Doesn't feel very welcome.

2023-05-15 05:29 UTC, janosimas approved these changes

2023-05-15 05:29 UTC, merged